/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksIndexRouteImport } from './routes/decks/index'
import { Route as DecksDeckIdRouteImport } from './routes/decks/$deckId'
import { Route as PokopiaIndexRouteImport } from './routes/pokopia/index'
import { Route as PokopiaHabitatsRouteImport } from './routes/pokopia/habitats'
import { Route as PokopiaVideosRouteImport } from './routes/pokopia/videos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/decks/$deckId',
  path: '/decks/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const PokopiaIndexRoute = PokopiaIndexRouteImport.update({
  id: '/pokopia/',
  path: '/pokopia/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokopiaHabitatsRoute = PokopiaHabitatsRouteImport.update({
  id: '/pokopia/habitats',
  path: '/pokopia/habitats',
  getParentRoute: () => rootRouteImport,
} as any)
const PokopiaVideosRoute = PokopiaVideosRouteImport.update({
  id: '/pokopia/videos',
  path: '/pokopia/videos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/pokopia/habitats': typeof PokopiaHabitatsRoute
  '/pokopia/videos': typeof PokopiaVideosRoute
  '/decks/': typeof DecksIndexRoute
  '/pokopia/': typeof PokopiaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/pokopia/habitats': typeof PokopiaHabitatsRoute
  '/pokopia/videos': typeof PokopiaVideosRoute
  '/decks': typeof DecksIndexRoute
  '/pokopia': typeof PokopiaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/pokopia/habitats': typeof PokopiaHabitatsRoute
  '/pokopia/videos': typeof PokopiaVideosRoute
  '/decks/': typeof DecksIndexRoute
  '/pokopia/': typeof PokopiaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decks/$deckId'
    | '/pokopia/habitats'
    | '/pokopia/videos'
    | '/decks/'
    | '/pokopia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/decks/$deckId'
    | '/pokopia/habitats'
    | '/pokopia/videos'
    | '/decks'
    | '/pokopia'
  id:
    | '__root__'
    | '/'
    | '/decks/$deckId'
    | '/pokopia/habitats'
    | '/pokopia/videos'
    | '/decks/'
    | '/pokopia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecksDeckIdRoute: typeof DecksDeckIdRoute
  PokopiaHabitatsRoute: typeof PokopiaHabitatsRoute
  PokopiaVideosRoute: typeof PokopiaVideosRoute
  DecksIndexRoute: typeof DecksIndexRoute
  PokopiaIndexRoute: typeof PokopiaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/': {
      id: '/decks/'
      path: '/decks'
      fullPath: '/decks/'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokopia/': {
      id: '/pokopia/'
      path: '/pokopia'
      fullPath: '/pokopia/'
      preLoaderRoute: typeof PokopiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokopia/habitats': {
      id: '/pokopia/habitats'
      path: '/pokopia/habitats'
      fullPath: '/pokopia/habitats'
      preLoaderRoute: typeof PokopiaHabitatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokopia/videos': {
      id: '/pokopia/videos'
      path: '/pokopia/videos'
      fullPath: '/pokopia/videos'
      preLoaderRoute: typeof PokopiaVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecksDeckIdRoute: DecksDeckIdRoute,
  PokopiaHabitatsRoute: PokopiaHabitatsRoute,
  PokopiaVideosRoute: PokopiaVideosRoute,
  DecksIndexRoute: DecksIndexRoute,
  PokopiaIndexRoute: PokopiaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
